---
title: "models_report"
author: "Thomas E. Metherell"
date: "2023-09-08"
format:
    html:
        code-fold: true
        toc: true
---

## Loading dependencies and targets

```{r dependencies}
library(targets)
library(knitr)

connection_ls_model <- tar_read(connection_ls_model)
connection_swbs_model <- tar_read(connection_swbs_model)
connection_anx_model <- tar_read(connection_anx_model)
connection_cesd_model <- tar_read(connection_cesd_model)
connection_sh_model <- tar_read(connection_sh_model)
connection_paykel_model <- tar_read(connection_paykel_model)

internet_ls_model <- tar_read(internet_ls_model)
internet_swbs_model <- tar_read(internet_swbs_model)
internet_anx_model <- tar_read(internet_anx_model)
internet_cesd_model <- tar_read(internet_cesd_model)
internet_sh_model <- tar_read(internet_sh_model)
internet_paykel_model <- tar_read(internet_paykel_model)
```

## Rounding values

```{r round}
for(obj_name in ls()){
    obj <- get(obj_name)

    for(i in 1:ncol(obj)){
        if(is.numeric(obj[, i])){
            obj[, i] <- round(obj[, i], 3)
        }
    }

    assign(obj_name, obj)
}
```

## Models for ability to stay connected during lockdown
### Life satisfaction

```{r conn_ls}
connection_ls_model |> kable(format = "markdown")
```

### CW-SWBS

```{r conn_swbs}
connection_swbs_model |> kable(format = "markdown")
```

### Anxiety

```{r conn_anx}
connection_anx_model |> kable(format = "markdown")
```

### CES-D

```{r conn_cesd}
connection_cesd_model |> kable(format = "markdown")
```

### Self-harm

```{r conn_sh}
connection_sh_model |> kable(format = "markdown")
```

### Paykel suicide scale

```{r conn_paykel}
connection_paykel_model |> kable(format = "markdown")
```

## Models for internet use frequency
### Life satisfaction

```{r int_ls}
internet_ls_model |> kable(format = "markdown")
```

### CW-SWBS

```{r int_swbs}
internet_swbs_model |> kable(format = "markdown")
```

### Anxiety

```{r int_anx}
internet_anx_model |> kable(format = "markdown")
```

### CES-D

```{r int_cesd}
internet_cesd_model |> kable(format = "markdown")
```

### Self-harm

```{r int_sh}
internet_sh_model |> kable(format = "markdown")
```

### Paykel suicide scale

```{r int_paykel}
internet_paykel_model |> kable(format = "markdown")
```